pipeline {
    agent any
environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-cred')
	}
    stages {
        stage('Clone repository') {
            steps {
                sh "rm -rf *"
               sh "git clone https://github.com/psdike/cicd-projects.git"
               
                //sh "cd cicd-projects"
               
            }
        }

        stage('Build Docker image') {
            
            steps {
                sh 'ls -la'
                sh 'docker build -t psdike/python:v${BUILD_NUMBER} -f cicd-projects/cicd-python-docker/Dockerfile .'
            }
        }

        stage('Login & Push Docker image') {
            
            steps {
 				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'

                sh 'docker push psdike/python:v${BUILD_NUMBER}'
            }
        }
        stage('Run Docker container') {
            steps {
                sh 'docker run -d psdike/python:v${BUILD_NUMBER}'
            }
        }

        stage('Show success message') {
            steps {
                echo 'Success'
            }
        }
    }
}
